using System.ComponentModel.DataAnnotations;

namespace DocAssistant.Gateway.Dtos.ChatMessage
{
    public record ChatMessageRequest
    {
        [Required]
        [MinLength(1, ErrorMessage = "Message cannot be empty")]
        [MaxLength(500, ErrorMessage = "Message cannot exceed 500 characters")]
        public string Content { get; set; } = string.Empty;

        // Role is set server-side to prevent injection attacks
        // User messages always have MessageRole.User
        // Assistant messages are generated by the AI service
    }
}
